package enums;

import fabricator.Alphanumeric;
import fabricator.Fabricator;

public enum Companies {
	APPLE("APPLE", 1),
	THINKING_MACHINES("THINKING_MACHINES", 2),
	RCA("RCA", 3),
	NETRONICS("NETRONICS", 4),
	TANDY_CORPORATION("TANDY_CORPORATION", 5),
	COMMODORE_INTERNATIONAL("COMMODORE_INTERNATIONAL", 6),
	MOS_TECHNOLOGY("MOS_TECHNOLOGY", 7),
	MICRO_INSTRUMENTATION_AND_TELEMETRY_SYSTEMS("MICRO_INSTRUMENTATION_AND_TELEMETRY_SYSTEMS", 8),
	IMS_ASSOCIATES("IMS_ASSOCIATES", 9),
	DIGITAL_EQUIPMENT_CORPORATION("DIGITAL_EQUIPMENT_CORPORATION", 10),
	LINCOLN_LABORATORY("LINCOLN_LABORATORY", 11),
	MOORE_SCHOOL_OF_ELECTRICAL_ENGINEERING("MOORE_SCHOOL_OF_ELECTRICAL_ENGINEERING", 12),
	IBM("IBM", 13),
	AMIGA_CORPORATION("AMIGA_CORPORATION", 14),
	CANON("CANON", 15),
	NOKIA("NOKIA", 16),
	SONY("SONY", 17),
	OQO("OQO", 18),
	NEXT("NEXT", 19),
	ATARI("ATARI", 20),
	ACORN_COMPUTER("ACORN_COMPUTER", 22),
	TIMEX_SINCLAIR("TIMEX_SINCLAIR", 23),
	NINTENDO("NINTENDO", 24),
	SINCLAIR_RESEARCH_LTD("SINCLAIR_RESEARCH_LTD", 25),
	XEROX("XEROX", 26),
	HEWLETT_PACKARD("HEWLETT_PACKARD", 27),
	ZEMMIX("ZEMMIX", 28),
	ACVS("ACVS", 29),
	SANYO("SANYO", 30),
	CRAY("CRAY", 31),
	EVANS_SUTHERLAND("EVANS_SUTHERLAND", 32),
	E_S_R_("E_S_R_", 33),
	OMRON("OMRON", 34),
	BBN_TECHNOLOGIES("BBN_TECHNOLOGIES", 35),
	LENOVO_GROUP("LENOVO_GROUP", 36),
	ASUS("ASUS", 37),
	AMSTRAD("AMSTRAD", 38),
	SUN_MICROSYSTEMS("SUN_MICROSYSTEMS", 39),
	TEXAS_INSTRUMENTS("TEXAS_INSTRUMENTS", 40),
	HTC_CORPORATION("HTC_CORPORATION", 41),
	RESEARCH_IN_MOTION("RESEARCH_IN_MOTION", 42),
	SAMSUNG_ELECTRONICS("SAMSUNG_ELECTRONICS", 43);

	public String getName() {
		return name;
	}

	private final String name;
	private int id;

	public int getId() {
		return id;
	}

	Companies(String name, int id) {
		this.name = name;
		this.id = id;
	}

	public static Companies getRandomCompany() {
		final Alphanumeric alphanumeric = Fabricator.alphaNumeric();
		final Companies[] companies = values();
		return companies[alphanumeric.randomInt(companies.length - 1)];
	}
}
